import { Component, OnInit } from '@angular/core';
import { Cube } from '../cube/cube.component';

interface ProductType {
  value: string;
  viewValue: string;
}

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss']
})
export class ProductsComponent implements OnInit {
  cubes: Cube[];
  productTypes: string[];
  products: Cube[];
  productNames: ProductType[];
  selected: ProductType;

  constructor() {
    this.productNames = [
      { value: 'kancelársky nábytok', viewValue: 'kancelársky nábytok' },
      { value: 'knižnice', viewValue: 'knižnice' },
      { value: 'komody', viewValue: 'komody' },
      { value: 'kuchyne', viewValue: 'kuchyne' },
      { value: 'kúpeľňové skrinky', viewValue: 'kúpeľňové skrinky' },
      { value: 'obývacie steny', viewValue: 'obývacie steny' },
      { value: 'postele', viewValue: 'postele' },
      { value: 'šatníky', viewValue: 'šatníky' },
      { value: 'schody', viewValue: 'schody' },
      { value: 'vešiakové steny', viewValue: 'vešiakové steny' },
      { value: 'vstavané skrine', viewValue: 'vstavané skrine' }
    ];
    this.selected = this.productNames[0];
    this.products = [
      { type: 'kancelársky nábytok', name: "kancelársky nábytok", image: "assets/products/kancelar/thumbnail-0.jpg" },
      { type: 'kancelársky nábytok', name: "kancelársky nábytok", image: "assets/products/kancelar/thumbnail-1.jpg" },
      { type: 'kancelársky nábytok', name: "kancelársky nábytok", image: "assets/products/kancelar/thumbnail-2.jpg" },
      { type: 'kancelársky nábytok', name: "kancelársky nábytok", image: "assets/products/kancelar/thumbnail-3.jpg" },
      { type: 'knižnice', name: "knižnice", image: "assets/products/kniznice/thumbnail-0.jpg" },
      { type: 'knižnice', name: "knižnice", image: "assets/products/kniznice/thumbnail-1.jpg" },
      { type: 'knižnice', name: "knižnice", image: "assets/products/kniznice/thumbnail-2.jpg" },
      { type: 'knižnice', name: "knižnice", image: "assets/products/kniznice/thumbnail-3.jpg" },
      { type: 'knižnice', name: "knižnice", image: "assets/products/kniznice/thumbnail-4.JPG" },
      { type: 'knižnice', name: "knižnice", image: "assets/products/kniznice/thumbnail-5.JPG" },
      { type: 'komody', name: "komody", image: "assets/products/komody/thumbnail-0.jpg" },
      { type: 'komody', name: "komody", image: "assets/products/komody/thumbnail-1.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-0.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-1.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-2.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-3.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-4.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-5.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-6.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-7.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-8.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-9.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-10.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-11.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-12.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-13.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-14.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-15.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-16.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-17.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-18.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-19.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-20.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-21.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-22.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-23.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-24.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-25.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-26.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-27.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-28.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-29.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-30.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-31.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-32.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-33.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-34.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-35.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-36.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-37.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-38.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-39.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-40.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-41.jpg" },
      { type: 'kuchyne', name: "kuchyne", image: "assets/products/kuchyne/thumbnail-42.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-0.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-1.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-2.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-3.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-4.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-5.jpg" },
      { type: 'kúpeľňové skrinky', name: "kúpeľňové skrinky", image: "assets/products/kupelnove_skrinky/thumbnail-6.jpg" },
      { type: 'obývacie steny', name: "obývacie steny", image: "assets/products/obyvacie_steny/thumbnail-0.jpg" },
      { type: 'obývacie steny', name: "obývacie steny", image: "assets/products/obyvacie_steny/thumbnail-1.jpg" },
      { type: 'obývacie steny', name: "obývacie steny", image: "assets/products/obyvacie_steny/thumbnail-2.jpg" },
      { type: 'obývacie steny', name: "obývacie steny", image: "assets/products/obyvacie_steny/thumbnail-3.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-0.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-1.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-2.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-3.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-4.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-5.jpg" },
      { type: 'postele', name: "postele", image: "assets/products/postele/thumbnail-6.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-0.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-1.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-2.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-3.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-4.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-5.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-6.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-7.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-8.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-9.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-10.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-11.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-12.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-13.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-14.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-15.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-16.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-17.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-18.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-19.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-20.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-21.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-22.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-23.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-24.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-25.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-26.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-27.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-28.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-29.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-30.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-31.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-32.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-33.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-34.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-35.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-36.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-37.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-38.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-39.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-40.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-41.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-42.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-43.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-44.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-45.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-46.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-47.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-48.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-49.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-50.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-51.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-52.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-53.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-54.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-55.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-56.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-57.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-58.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-59.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-60.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-61.jpg" },
      { type: 'šatníky', name: "šatníky", image: "assets/products/satniky/thumbnail-62.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-0.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-1.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-2.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-3.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-4.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-5.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-6.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-7.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-8.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-9.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-10.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-11.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-12.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-13.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-14.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-15.jpg" },
      { type: 'schody', name: "schody", image: "assets/products/schody/thumbnail-16.jpg" },
      { type: 'stoly', name: "stoly", image: "assets/products/stoly/thumbnail-0.jpg" },
      { type: 'stoly', name: "stoly", image: "assets/products/stoly/thumbnail-1.jpg" },
      { type: 'stoly', name: "stoly", image: "assets/products/stoly/thumbnail-2.jpg" },
      { type: 'stoly', name: "stoly", image: "assets/products/stoly/thumbnail-3.jpeg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-0.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-1.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-2.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-3.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-4.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-5.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-6.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-7.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-8.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-9.jpg" },
      { type: 'vešiakové steny', name: "vešiakové steny", image: "assets/products/vesiakove_steny/thumbnail-9.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-0.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-1.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-2.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-3.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-4.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-5.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-6.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-7.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-8.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-9.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-10.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-11.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-12.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-13.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-14.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-15.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-16.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-17.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-18.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-19.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-20.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-21.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-22.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-23.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-24.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-25.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-26.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-27.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-28.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-29.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-30.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-31.jpg" },
      { type: 'vstavané skrine', name: "vstavané skrine", image: "assets/products/vstavene_skrine/thumbnail-32.jpg" },
    ]
    this.cubes = this.products
    this.productTypes = this.cubes.map(it => it.type).reduce<string[]>((acc, item) => {
      if (!acc.some(it => it == item)) {
        acc.push(item)
      }
      return acc
    }, [])
    this.selectProductHandler("kancelársky nábytok")
  }

  selectProductHandler = (productType: string) => {
    let selectedCubes = this.products.filter(it => it.type == productType)
    this.cubes = selectedCubes
  }

  ngOnInit(): void {

  }

}
